// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNtpXSmuMOaU-fWXu_7fVbdETpj16p2XU',
    appId: '1:903934951832:web:893e35508d68b86b89ebed',
    messagingSenderId: '903934951832',
    projectId: 'blog-603f8',
    authDomain: 'blog-603f8.firebaseapp.com',
    storageBucket: 'blog-603f8.appspot.com',
    measurementId: 'G-T633H4VQ3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn16zLH_7PMGZ0VwIaDNq7Zjm5z1o68jw',
    appId: '1:903934951832:android:6b080c7a6e7481c089ebed',
    messagingSenderId: '903934951832',
    projectId: 'blog-603f8',
    storageBucket: 'blog-603f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW-H6DT_f9I21yksXskY3QnbIHS6llbho',
    appId: '1:903934951832:ios:969dc14b578f529e89ebed',
    messagingSenderId: '903934951832',
    projectId: 'blog-603f8',
    storageBucket: 'blog-603f8.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );
}
